#!/bin/bash

logFile="/var/log/apache2/access.log"

function displayAllLogs(){
    cat "$logFile"
}

function displayOnlyIPs(){
    cat "$logFile" | cut -d ' ' -f 1 | sort -n | uniq -c
}

# function: displayOnlyPages:
# like displayOnlyIPs - but only pages


function displayOnlyPages(){
    cat "$logFile" | cut -d ' ' -f 7 | grep "\.html" | sort | uniq
}

function histogram(){
    local visitsPerDay=$(cat "$logFile" | cut -d " " -f 4,1 | tr -d '[' | sort | uniq)
    :> newtemp.txt
    echo "$visitsPerDay" | while read -r line; do
        local withoutHours=$(echo "$line" | cut -d " " -f 2 | cut -d ":" -f 1)
        local IP=$(echo "$line" | cut -d " " -f 1)
        local newLine="$IP $withoutHours"
        echo "$newLine" >> newtemp.txt
    done
    cat "newtemp.txt" | sort -n | uniq -c
}

# function: frequentVisitors: 
# Only display the IPs that have more than 10 visits
# You can either call histogram and process the results,
# Or make a whole new function. Do not forget to separate the 
# number and check with a condition whether it is greater than 10
# the output should be almost identical to histogram
# only with daily number of visits that are greater than 10 

# function: suspiciousVisitors
# Manually make a list of indicators of attack (ioc.txt)
# filter the records with this indicators of attack
# only display the unique count of IP addresses.  
# Hint: there are examples in slides

# Keep in mind that I have selected long way of doing things to 
# demonstrate loops, functions, etc. If you can do things simpler,
# it is welcomed.

function frequentVisitors(){
    local visits=$(cat "$logFile" | cut -d ' ' -f 1 | sort | uniq -c)
    echo "$visits" | while read -r count ip; do
        if (( count > 10 )); then
            echo "$count $ip"
        fi
    done
}

function suspiciousVisitors(){
    if [[ ! -f ioc.txt ]]; then
        echo "file not found"
        return
    fi

    local suspiciousIPs=$(cat "$logFile" | grep -f ioc.txt | cut -d ' ' -f 1 | sort | uniq -c)
    echo "$suspiciousIPs"
}

while :
do
    echo "Please select an option:"
    echo "[1] Display all Logs"
    echo "[2] Display only IPs"
    echo "[3] Display only Pages"
    echo "[4] Histogram"
    echo "[5] Frequent Visitors"
    echo "[6] Suspicious Visitors"
    echo "[7] Quit"

    read userInput
    echo ""

    if [[ "$userInput" == "7" ]]; then
        echo "Goodbye"
        break

    elif [[ "$userInput" == "1" ]]; then
        echo "Displaying all logs:"
        displayAllLogs

    elif [[ "$userInput" == "2" ]]; then
        echo "Displaying only IPs:"
        displayOnlyIPs

    elif [[ "$userInput" == "3" ]]; then
        echo "Displaying only Pages:"
        displayOnlyPages

    elif [[ "$userInput" == "4" ]]; then
        echo "Histogram:"
        histogram

    elif [[ "$userInput" == "5" ]]; then
        echo "Frequent Visitors:"
        frequentVisitors

    elif [[ "$userInput" == "6" ]]; then
        echo "Suspicious Visitors:"
        suspiciousVisitors

    else
        echo "Invalid input."
    fi
done
